"""Assemble the self-contained installer from the maintained components."""

import argparse
import ast
import os
from pathlib import Path
import re
import stat
import tempfile


ROOT = Path(__file__).resolve().parents[1]
PARTS = (
    "Bootstrap/config.sh",
    "Bootstrap/platform.sh",
    "Core/state.sh",
    "Trust/anchor.sh.in",
    "Trust/repositories.sh",
    "Packages/transactions.sh.in",
    "Updates/preparation.sh.in",
    "Updates/diagnostics.sh.in",
    "Web/isolation.sh.in",
    "SSH/policy.sh.in",
    "SSH/keys.sh.in",
    "SSH/accounts.sh.in",
    "Bootstrap/verifier.sh.in",
    "Recovery/reconcile.sh",
    "Recovery/install.sh",
    "Recovery/finalize.sh",
    "Recovery/worker.sh",
    "Bootstrap/main.sh",
)
PAYLOADS = {
    "Trust/vendor-key.asc": "S4_VENDOR_KEY",
    "Packages/admission.py": "PY",
    "Packages/download.py": "PY",
    "Updates/store.py": "PY",
    "Updates/effects.py": "PY",
    "Updates/baselines.py": "PY",
    "Updates/rpm_test.py": "PY",
    "Updates/capacity.py": "PY",
    "Updates/interpreters.py": "PY",
    "Updates/removals.py": "PY",
    "Updates/versions.py": "PY",
    "Web/policy.py": "PY",
    "SSH/policy.py": "PY",
    "SSH/service.py": "PY",
    "SSH/keys.py": "PY",
    "SSH/accounts.py": "PY",
    "SSH/home.py": "PY",
    "Web/relay.py": "'''",
    "Updates/plan.py": "PY",
    "Updates/sandbox.py": "PY",
    "Bootstrap/integrity.py": "PY",
    "Bootstrap/participation.py": "PY",
}
WORKER_TARGET = "Web/relay.py"
WORKER_TEMPLATE = "Web/relay.py.in"
WORKER_HELPER = "Web/runtime.py"  # Retained name for the runtime fixture boundary.
WORKER_HELPERS = (WORKER_HELPER, "Web/memory.py", "Web/descriptors.py", "Web/limits.py")
INPUTS = (*PARTS, *(name for name in PAYLOADS if name != WORKER_TARGET), WORKER_TEMPLATE, *WORKER_HELPERS)
INCLUDE = re.compile(rb"# @s4-include ([A-Za-z0-9_./-]+)\n")
TARGET = "azurelinux3s4.sh"
OUTPUTS = {TARGET: 0o755, WORKER_TARGET: 0o644}


def read_source(root, relative):
    path = root / relative
    if path.is_symlink() or not path.is_file():
        raise ValueError("assembly input must be a regular file: " + relative)
    data = path.read_bytes()
    data.decode("utf-8")
    if not data.endswith(b"\n") or b"\r" in data or b"\0" in data:
        raise ValueError("assembly input must use UTF-8, LF and a final newline: " + relative)
    return data


def assemble_worker(root=ROOT):
    helpers = {}
    for name in WORKER_HELPERS:
        data = read_source(root, name)
        ast.parse(data, filename=name)
        if b"@s4-include" in data:
            raise ValueError("worker helper cannot request assembly inputs")
        helpers[name] = data
    pieces, used = [], set()
    for line in read_source(root, WORKER_TEMPLATE).splitlines(keepends=True):
        match = INCLUDE.fullmatch(line)
        if match:
            name = match[1].decode("ascii")
            if name not in helpers or name in used:
                raise ValueError("unknown or repeated worker helper include")
            pieces.append(helpers[name])
            used.add(name)
        else:
            if b"@s4-include" in line:
                raise ValueError("malformed worker runtime include")
            pieces.append(line)
    if used != helpers.keys():
        raise ValueError("missing worker helper include")
    data = b"# Generated by Bootstrap/pack.py from Web/relay.py.in and declared Web helpers.\n" + b"".join(pieces)
    ast.parse(data, filename=WORKER_TARGET)
    return data


def artifacts(root=ROOT):
    worker = assemble_worker(root)
    used = set()
    pieces = []
    for index, relative in enumerate(PARTS):
        for line in read_source(root, relative).splitlines(keepends=True):
            match = INCLUDE.fullmatch(line)
            if not match:
                if b"@s4-include" in line:
                    raise ValueError("malformed assembly directive in " + relative)
                pieces.append(line)
                continue
            payload = match[1].decode("ascii")
            if payload not in PAYLOADS or payload in used:
                raise ValueError("unknown or repeated assembly payload: " + payload)
            data = worker if payload == WORKER_TARGET else read_source(root, payload)
            if (PAYLOADS[payload].encode() in data.splitlines()
                    or b"@s4-include" in data
                    or (PAYLOADS[payload] == "'''" and (b"'''" in data or b"PY" in data.splitlines()))):
                raise ValueError("payload collides with its assembly boundary: " + payload)
            if payload.endswith(".py"):
                ast.parse(data, filename=payload)
            pieces.append(data)
            used.add(payload)
        if index + 1 < len(PARTS):
            pieces.append(b"\n")
    if used != PAYLOADS.keys():
        raise ValueError("assembly is missing declared payloads: " + ", ".join(sorted(PAYLOADS.keys() - used)))
    return {TARGET: b"".join(pieces), WORKER_TARGET: worker}


def assemble(root=ROOT):
    return artifacts(root)[TARGET]


def target_path(root, relative=TARGET):
    path = root / relative
    if path.is_symlink() or (path.exists() and not path.is_file()):
        raise ValueError("installer target must be a regular file")
    return path


def publish(root, outputs):
    # Precheck both operator leaves, stage complete files, then replace each.
    # Each replace is atomic; the pair is not a crash-durable transaction.
    targets = {name: target_path(root, name) for name in OUTPUTS}
    temporary = {}
    try:
        for name, mode in OUTPUTS.items():
            with tempfile.NamedTemporaryFile(prefix=".azurelinux3s4-", suffix=".tmp",
                                             dir=targets[name].parent, delete=False) as stream:
                temporary[name] = Path(stream.name)
                stream.write(outputs[name])
                stream.flush()
                os.fchmod(stream.fileno(), mode)
        for name in OUTPUTS:
            os.replace(temporary[name], targets[name])
    finally:
        for path in temporary.values():
            path.unlink(missing_ok=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="refuse if the installer or worker differs from maintained sources")
    args = parser.parse_args()
    try:
        outputs = artifacts()
        if args.check:
            for name, mode in OUTPUTS.items():
                target = target_path(ROOT, name)
                if (not target.is_file() or target.read_bytes() != outputs[name]
                        or stat.S_IMODE(target.stat().st_mode) != mode):
                    parser.exit(1, name + " differs from its sources or mode; run Bootstrap/pack.py\n")
        else:
            publish(ROOT, outputs)
    except (OSError, ValueError, SyntaxError) as error:
        parser.exit(1, "Installer assembly failed: " + str(error) + "\n")


if __name__ == "__main__":
    main()
