# Generated by Bootstrap/pack.py from Web/relay.py.in and declared Web helpers.
"""One accepted TCP connection to one Unix backend; no reconnect after sealing.

Candidate worker only. Credential/path observations do not authenticate the
runtime, authorize a caller or establish systemd/LSM confinement.
"""

import ctypes
import errno
import grp
import os
import platform
import pwd
import resource
import selectors
import socket
import stat
import struct
import sys
import time


"""Observe loaded native file identities; no signature or memory attestation."""

import hashlib
import os
import platform
import re
import signal
import stat
import struct
import time


RUNTIME_OWNER = 0
RUNTIME_MAP_BYTES = 1024 * 1024
RUNTIME_IMAGES = 128
RUNTIME_IMAGE_BYTES = 64 * 1024 * 1024
RUNTIME_TOTAL_BYTES = 256 * 1024 * 1024
RUNTIME_OBSERVE_SECONDS = 30
STARTUP_SECONDS = 60


class RuntimeStartup:
    """A sole worker's startup timer; forwarding has its separate deadline."""

    def __init__(self):
        self.armed = False
        self.handler = self.expired

    def expired(self, number, frame):
        raise TimeoutError("relay startup deadline reached")

    def __enter__(self):
        if (signal.getsignal(signal.SIGALRM) != signal.SIG_DFL
                or signal.getitimer(signal.ITIMER_REAL) != (0.0, 0.0)
                or signal.SIGALRM in signal.pthread_sigmask(signal.SIG_BLOCK, ())):
            raise ValueError("relay startup signal context refused")
        signal.signal(signal.SIGALRM, self.handler)
        try:
            signal.setitimer(signal.ITIMER_REAL, STARTUP_SECONDS)
        except BaseException:
            signal.signal(signal.SIGALRM, signal.SIG_DFL)
            raise
        self.armed = True
        remaining, interval = signal.getitimer(signal.ITIMER_REAL)
        if signal.getsignal(signal.SIGALRM) is not self.handler or not 0 < remaining <= STARTUP_SECONDS or interval:
            self.disarm()
            raise RuntimeError("relay startup handler was not installed")
        return self

    def disarm(self):
        if not self.armed:
            return
        signal.setitimer(signal.ITIMER_REAL, 0)
        previous = signal.signal(signal.SIGALRM, signal.SIG_DFL)
        self.armed = False
        if (previous is not self.handler or signal.getitimer(signal.ITIMER_REAL) != (0.0, 0.0)
                or signal.getsignal(signal.SIGALRM) != signal.SIG_DFL):
            raise RuntimeError("relay startup timer retirement was not observed")

    def __exit__(self, *exception):
        self.disarm()


def runtime_path(path):
    if (not isinstance(path, str) or not path.startswith("/") or len(path.encode()) > 4096
            or not path.isascii() or any(ord(character) < 33 or ord(character) > 126 for character in path)
            or "\\" in path or path.endswith(" (deleted)")):
        raise ValueError("unsupported runtime image path")
    parts = path[1:].split("/")
    if len(parts) > 64 or any(part in ("", ".", "..") for part in parts):
        raise ValueError("noncanonical runtime image path")
    return parts


def runtime_maps(data=None):
    if data is None:
        descriptor = os.open("/proc/self/maps", os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC)
        try:
            if not stat.S_ISREG(os.fstat(descriptor).st_mode):
                raise ValueError("runtime maps is not a regular proc observation")
            blocks, total = [], 0
            while block := os.read(descriptor, min(65536, RUNTIME_MAP_BYTES + 1 - total)):
                blocks.append(block)
                total += len(block)
                if total > RUNTIME_MAP_BYTES:
                    raise ValueError("runtime maps observation exceeds its bound")
            data = b"".join(blocks)
        finally:
            os.close(descriptor)
    if not isinstance(data, bytes) or not data or len(data) > RUNTIME_MAP_BYTES or not data.endswith(b"\n"):
        raise ValueError("runtime maps observation exceeds its bound or is truncated")
    records, images, paths, mapped_paths = [], {}, {}, {}
    lines = data.splitlines()
    if len(lines) > 4096:
        raise ValueError("runtime mapping inventory exceeds its bound")
    for line in lines:
        fields = line.split(None, 5)
        if len(fields) < 5:
            raise ValueError("malformed runtime mapping")
        address, permissions, offset, device, inode = fields[:5]
        raw_path = fields[5] if len(fields) == 6 else b""
        if (not re.fullmatch(rb"[0-9a-f]+-[0-9a-f]+", address)
                or not re.fullmatch(rb"[r-][w-][x-][ps]", permissions)
                or not re.fullmatch(rb"[0-9a-f]+", offset)
                or not re.fullmatch(rb"[0-9a-f]+:[0-9a-f]+", device)
                or not re.fullmatch(rb"[0-9]+", inode)):
            raise ValueError("malformed runtime mapping fields")
        start, end = (int(value, 16) for value in address.split(b"-"))
        major, minor = (int(value, 16) for value in device.split(b":"))
        identity = major, minor, int(inode)
        if not 0 <= start < end < 1 << 64 or any(value >= 1 << 64 for value in (*identity, int(offset, 16))):
            raise ValueError("runtime mapping integer bounds refused")
        if permissions[1:3] == b"wx":
            raise ValueError("writable executable runtime mapping refused")
        # Only executable image ranges are observed here. Read-only/writable
        # data mappings may split/merge during ordinary allocator activity.
        if permissions[2:3] != b"x":
            continue
        path = raw_path.decode("ascii")
        if "x" in permissions.decode() and identity[2] == 0:
            allowed = {"[vdso]", "[vsyscall]"} if platform.machine() == "x86_64" else {"[vdso]"}
            if path not in allowed:
                raise ValueError("anonymous executable runtime mapping refused")
            records.append((start, end, permissions.decode(), int(offset, 16), identity, path))
        if identity[2]:
            runtime_path(path)
            if path in paths and paths[path] != identity:
                raise ValueError("runtime path has ambiguous mapped identity")
            if identity in mapped_paths and mapped_paths[identity] != path:
                raise ValueError("runtime inode has ambiguous mapped paths")
            paths[path] = identity
            mapped_paths[identity] = path
            records.append((start, end, permissions.decode(), int(offset, 16), identity, path))
            images[identity] = path
            if len(paths) > RUNTIME_IMAGES:
                raise ValueError("runtime image inventory exceeds its bound")
        if len(records) > 4096:
            raise ValueError("runtime mapping inventory exceeds its bound")
    if not images:
        raise ValueError("runtime has no mapped executable image")
    return tuple(records), images


def runtime_root():
    return os.open("/", os.O_PATH | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC)


def runtime_mount(descriptor):
    with open(f"/proc/self/fdinfo/{descriptor}", "rb") as stream:
        data = stream.read(8193)
    values = [line.split(b":", 1)[1].strip() for line in data.splitlines() if line.startswith(b"mnt_id:")]
    if len(data) > 8192 or len(values) != 1 or not values[0].isdigit():
        raise ValueError("runtime descriptor mount identity unavailable")
    return int(values[0])


def runtime_identity(value):
    return value.st_dev, value.st_ino, value.st_mode, value.st_uid, value.st_gid


def runtime_walk(path):
    descriptors, trace = [], []
    try:
        descriptors.append(runtime_root())
        parts = runtime_path(path)
        for index, name in enumerate((None, *parts)):
            if name is not None:
                descriptors.append(os.open(name, os.O_PATH | os.O_NOFOLLOW | os.O_CLOEXEC,
                                           dir_fd=descriptors[-1]))
            value = os.fstat(descriptors[-1])
            if value.st_uid != RUNTIME_OWNER or value.st_mode & 0o022:
                raise ValueError("unprotected runtime image ancestry or ownership")
            if index < len(parts):
                if not stat.S_ISDIR(value.st_mode):
                    raise ValueError("runtime image ancestry is not an alias-free directory")
            elif not stat.S_ISREG(value.st_mode):
                raise ValueError("runtime image leaf is not a regular file")
            trace.append((runtime_identity(value), runtime_mount(descriptors[-1])))
        return descriptors, trace
    except BaseException:
        for descriptor in reversed(descriptors):
            os.close(descriptor)
        raise


def runtime_image(path, expected, deadline):
    descriptors, before = runtime_walk(path)
    opened = None
    try:
        leaf = os.fstat(descriptors[-1])
        if ((os.major(leaf.st_dev), os.minor(leaf.st_dev), leaf.st_ino) != expected
                or not 64 <= leaf.st_size <= RUNTIME_IMAGE_BYTES):
            raise ValueError("runtime image differs from mapped inode or size bound")
        opened = os.open(f"/proc/self/fd/{descriptors[-1]}", os.O_RDONLY | os.O_CLOEXEC)
        value = os.fstat(opened)
        if runtime_identity(value) != runtime_identity(leaf):
            raise ValueError("runtime hash descriptor differs from held inode")
        header = os.read(opened, 64)
        machine = {"x86_64": 62, "aarch64": 183}.get(platform.machine())
        if (len(header) != 64 or header[:7] != b"\x7fELF\x02\x01\x01"
                or struct.unpack_from("<HHI", header, 16) not in ((2, machine, 1), (3, machine, 1))
                or struct.unpack_from("<H", header, 52)[0] != 64):
            raise ValueError("runtime image lacks the supported native ELF header")
        digest, total = hashlib.sha256(header), len(header)
        while block := os.read(opened, 1024 * 1024):
            total += len(block)
            if total > RUNTIME_IMAGE_BYTES or time.monotonic() >= deadline:
                raise ValueError("runtime image read exceeds its byte/time bound")
            digest.update(block)
        after = os.fstat(opened)
        content_identity = lambda item: (runtime_identity(item), item.st_size, item.st_mtime_ns, item.st_ctime_ns)
        if content_identity(value) != content_identity(after) or total != value.st_size:
            raise ValueError("runtime image changed while hashing")
        checked_descriptors, checked_trace = runtime_walk(path)
        try:
            if (checked_trace != before
                    or content_identity(os.fstat(checked_descriptors[-1])) != content_identity(after)
                    or any(runtime_identity(os.fstat(fd)) != entry[0] or runtime_mount(fd) != entry[1]
                           for fd, entry in zip(descriptors, before))):
                raise ValueError("runtime image path or mount changed during observation")
        finally:
            for descriptor in reversed(checked_descriptors):
                os.close(descriptor)
        return {"path": path, "mapped_identity": expected, "bytes": total,
                "sha256": digest.hexdigest(), "file_identity": content_identity(after), "ancestry": before}
    finally:
        if opened is not None:
            os.close(opened)
        for descriptor in reversed(descriptors):
            os.close(descriptor)


def observe_runtime():
    if platform.machine() not in ("x86_64", "aarch64"):
        raise ValueError("unsupported runtime ELF architecture")
    # Warm the digest provider before taking the loaded-image snapshot.
    hashlib.sha256(b"").digest()
    deadline = time.monotonic() + RUNTIME_OBSERVE_SECONDS
    before, images = runtime_maps()
    executable = os.open("/proc/self/exe", os.O_PATH | os.O_CLOEXEC)  # Trusted kernel magic link.
    try:
        value = os.fstat(executable)
        identity = os.major(value.st_dev), os.minor(value.st_dev), value.st_ino
        path = os.readlink("/proc/self/exe")
        runtime_path(path)
        if identity not in images or images[identity] != path:
            raise ValueError("interpreter executable is not bound to mapped runtime")
        observations, total = [], 0
        for key, name in sorted(images.items()):
            if time.monotonic() >= deadline:
                raise ValueError("runtime observation deadline reached")
            observed = runtime_image(name, key, deadline)
            total += observed["bytes"]
            if total > RUNTIME_TOTAL_BYTES:
                raise ValueError("runtime image batch exceeds its byte bound")
            observations.append(observed)
        after, final_images = runtime_maps()
        if (before != after or images != final_images or os.readlink("/proc/self/exe") != path
                or runtime_identity(os.fstat(executable)) != runtime_identity(value)
                or time.monotonic() >= deadline):
            raise ValueError("loaded runtime changed during file observation")
        return {"images": observations, "interpreter_path": path, "interpreter_identity": identity,
                "total_bytes": total, "native_runtime_authenticated": False,
                "memory_contents_attested": False, "dependency_closure_complete": False,
                "installation_authorized": False, "server_ready": False}
    finally:
        os.close(executable)
"""Native MDWE admission and live challenges; no code bytes are executed."""

import ctypes
import errno
import os
import platform


def protect_memory():
    if (platform.machine() not in ("x86_64", "aarch64")
            or ctypes.sizeof(ctypes.c_void_p) != 8 or ctypes.sizeof(ctypes.c_long) != 8):
        raise ValueError("unsupported MDWE native architecture or ABI")
    libc = ctypes.CDLL(None, use_errno=True)
    libc.prctl.argtypes = [ctypes.c_int, ctypes.c_ulong, ctypes.c_ulong, ctypes.c_ulong, ctypes.c_ulong]
    libc.prctl.restype = ctypes.c_int
    libc.mmap.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_int, ctypes.c_int, ctypes.c_int, ctypes.c_long]
    libc.mmap.restype = ctypes.c_void_p
    libc.mprotect.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_int]
    libc.mprotect.restype = ctypes.c_int
    libc.munmap.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    libc.munmap.restype = ctypes.c_int
    state = libc.prctl(66, 0, 0, 0, 0)  # PR_GET_MDWE
    if state < 0:
        raise OSError(ctypes.get_errno(), "MDWE query refused")
    if state not in (0, 1):
        # Refuse NO_INHERIT/unknown flags; never weaken an inherited policy.
        raise ValueError("unsupported inherited MDWE mask")
    size = os.sysconf("SC_PAGE_SIZE")
    if not 4096 <= size <= 65536 or size & (size - 1):
        raise ValueError("unsupported MDWE challenge page size")
    failed = ctypes.c_void_p(-1).value
    writable = libc.mmap(None, size, 3, 0x22, -1, 0)  # Private anonymous R/W.
    if writable == failed:
        raise OSError(ctypes.get_errno(), "MDWE writable-page baseline refused")
    try:
        if libc.mprotect(writable, size, 3) != 0:
            raise OSError(ctypes.get_errno(), "MDWE writable-page baseline protection refused")
        if libc.prctl(65, 1, 0, 0, 0) != 0:  # PR_SET_MDWE/REFUSE_EXEC_GAIN, inheritable.
            raise OSError(ctypes.get_errno(), "MDWE installation refused")
        if libc.prctl(66, 0, 0, 0, 0) != 1:
            raise RuntimeError("MDWE protection mask was not observed")
        ctypes.set_errno(0)
        if libc.mprotect(writable, size, 5) != -1 or ctypes.get_errno() != errno.EACCES:
            raise RuntimeError("MDWE execute-gain challenge failed")
        ctypes.set_errno(0)
        created = libc.mmap(None, size, 7, 0x22, -1, 0)
        observed_errno = ctypes.get_errno()
        if created != failed:
            if libc.munmap(created, size) != 0:
                raise OSError(ctypes.get_errno(), "MDWE unexpected-page cleanup refused")
            raise RuntimeError("MDWE writable-executable challenge failed")
        if observed_errno != errno.EACCES:
            raise RuntimeError("MDWE writable-executable challenge failed")
        if libc.mprotect(writable, size, 3) != 0:
            raise OSError(ctypes.get_errno(), "MDWE data-page compatibility refused")
        if libc.prctl(66, 0, 0, 0, 0) != 1:
            raise RuntimeError("MDWE final protection mask was not observed")
    finally:
        if libc.munmap(writable, size) != 0:
            raise OSError(ctypes.get_errno(), "MDWE challenge cleanup refused")
    return 1
"""Final descriptor duplication/mutation refusal and nonmutating witnesses."""

import ctypes
import errno
import os


DESCRIPTOR_DENIED = ("dup", "dup2", "dup3")


def add_descriptor_rules(lib, context):
    if ctypes.sizeof(ctypes.c_void_p) != 8 or ctypes.sizeof(ctypes.c_long) != 8:
        raise ValueError("unsupported descriptor native ABI")
    number = lib.seccomp_syscall_resolve_name(b"fcntl")
    if number == -1:
        raise ValueError("unknown syscall: fcntl")
    # Allow only exact F_GETFD=1/F_GETFL=3. Separate single-argument rules
    # avoid unsupported repeated comparisons on one argument. Full-width
    # comparisons also refuse high-bit aliases of kernel-truncated commands.
    for operation, value in ((2, 1), (4, 2), (6, 3)):  # LT1, EQ2, GT3.
        comparison = Comparison(1, operation, value, 0)
        checked(lib.seccomp_rule_add_array(context, 0x50000 | errno.EPERM,
                                           number, 1, ctypes.byref(comparison)))


def verify_descriptors(descriptors):
    if (len(descriptors) != 2
            or any(type(fd) is not int or not 0 <= fd <= 0x7fffffff for fd in descriptors)
            or len(set(descriptors)) != 2):
        raise ValueError("two distinct descriptor observations are required")
    libc = ctypes.CDLL(None, use_errno=True)
    libc.dup.argtypes, libc.dup.restype = [ctypes.c_int], ctypes.c_int
    libc.dup2.argtypes, libc.dup2.restype = [ctypes.c_int, ctypes.c_int], ctypes.c_int
    libc.dup3.argtypes, libc.dup3.restype = [ctypes.c_int] * 3, ctypes.c_int
    libc.fcntl.argtypes, libc.fcntl.restype = [ctypes.c_int, ctypes.c_int, ctypes.c_long], ctypes.c_int
    # Invalid source FDs make all probes noncreating/nonmutating even when
    # a rule is absent. EBADF/EINVAL cannot certify the filter's EPERM.
    challenges = (
        ("dup", libc.dup, (-1,)),
        ("dup2", libc.dup2, (-1, -1)),
        ("dup3", libc.dup3, (-1, -1, 0)),
        ("fcntl-dupfd", libc.fcntl, (-1, 0, 0)),
        ("fcntl-setfd", libc.fcntl, (-1, 2, 0)),
        ("fcntl-setfl", libc.fcntl, (-1, 4, 0)),
        ("fcntl-dupfd-cloexec", libc.fcntl, (-1, 1030, 0)),
    )
    for name, operation, arguments in challenges:
        ctypes.set_errno(0)
        if operation(*arguments) != -1 or ctypes.get_errno() != errno.EPERM:
            raise RuntimeError("descriptor denial challenge failed: " + name)
    for descriptor in descriptors:
        flags = libc.fcntl(descriptor, 1, 0)
        status = libc.fcntl(descriptor, 3, 0)
        if flags not in (0, 1) or status < 0 or not status & os.O_NONBLOCK:
            raise RuntimeError("descriptor query/nonblocking state refused")
"""Checked child-only descriptor budgets and final resource-setter refusal."""

import ctypes
import errno
import platform
import resource


FD_STARTUP_LIMIT = 256
FD_FORWARD_LIMIT = 16
RESOURCE_DENIED = ("setrlimit",)


class ResourceLimit64(ctypes.Structure):
    _fields_ = [("current", ctypes.c_uint64), ("maximum", ctypes.c_uint64)]


def resource_abi():
    if (platform.machine() not in ("x86_64", "aarch64")
            or ctypes.sizeof(ctypes.c_void_p) != 8 or ctypes.sizeof(ctypes.c_ulong) != 8
            or resource.RLIMIT_NOFILE != 7):
        raise ValueError("unsupported resource native ABI")


def bound_descriptors(ceiling, retained=()):
    resource_abi()
    if ceiling not in (FD_STARTUP_LIMIT, FD_FORWARD_LIMIT):
        raise ValueError("unsupported descriptor resource budget")
    if any(type(fd) is not int or not 0 <= fd <= 0x7fffffff for fd in retained):
        raise ValueError("invalid retained descriptor observation")
    observed = resource.getrlimit(resource.RLIMIT_NOFILE)
    if (not isinstance(observed, tuple) or len(observed) != 2
            or any(type(value) is not int or (value != resource.RLIM_INFINITY and not 0 <= value < 1 << 64)
                   for value in observed)):
        raise ValueError("descriptor resource observations refused")
    normalized = tuple((1 << 64) - 1 if value == resource.RLIM_INFINITY else value for value in observed)
    if normalized[0] > normalized[1]:
        raise ValueError("descriptor resource observations refused")
    expected = tuple(min(value, ceiling) for value in normalized)
    # RLIMIT_NOFILE does not close already-open high descriptors. The caller
    # scrubs extras first, and every kept channel must be below the new bound.
    if any(fd >= expected[0] for fd in retained):
        raise ValueError("retained descriptor exceeds resource budget")
    resource.setrlimit(resource.RLIMIT_NOFILE, expected)
    if resource.getrlimit(resource.RLIMIT_NOFILE) != expected:
        raise RuntimeError("descriptor resource limit was not observed")
    return expected


def add_resource_rules(lib, context):
    resource_abi()
    number = lib.seccomp_syscall_resolve_name(b"prlimit64")
    if number == -1:
        raise ValueError("unknown syscall: prlimit64")
    # NULL new_limit means query only. Compare pointer presence, never its
    # contents: every non-NULL update request is denied for every resource/PID.
    comparison = Comparison(2, 1, 0, 0)  # SCMP_CMP_NE, new_limit != NULL.
    checked(lib.seccomp_rule_add_array(context, 0x50000 | errno.EPERM,
                                       number, 1, ctypes.byref(comparison)))


def native_resource_api():
    libc = ctypes.CDLL(None, use_errno=True)
    try:
        libc.prlimit64.argtypes = [ctypes.c_int, ctypes.c_int,
                                  ctypes.POINTER(ResourceLimit64), ctypes.POINTER(ResourceLimit64)]
        libc.prlimit64.restype = ctypes.c_int
        libc.syscall.argtypes, libc.syscall.restype = [ctypes.c_long], ctypes.c_long
    except AttributeError as error:
        raise ValueError("native resource interfaces unavailable") from error
    return libc


def verify_resource_limits(expected):
    resource_abi()
    if (not isinstance(expected, tuple) or len(expected) != 2
            or any(type(value) is not int for value in expected)
            or not 0 < expected[0] <= expected[1] <= FD_FORWARD_LIMIT):
        raise ValueError("invalid forwarding descriptor budget")
    if resource.getrlimit(resource.RLIMIT_NOFILE) != expected:
        raise RuntimeError("descriptor resource read-back refused")
    libc = native_resource_api()
    observed = ResourceLimit64()
    if (libc.prlimit64(0, 7, None, ctypes.byref(observed)) != 0
            or (observed.current, observed.maximum) != expected):
        raise RuntimeError("native descriptor resource query refused")
    lib = ctypes.CDLL("libseccomp.so.2")
    lib.seccomp_syscall_resolve_name.argtypes, lib.seccomp_syscall_resolve_name.restype = [ctypes.c_char_p], ctypes.c_int
    invalid = ResourceLimit64(0, 0)
    # Raw syscalls avoid libc setrlimit being redirected through prlimit64.
    # Resource -1 is invalid even if a filter rule is absent; no limit changes.
    probes = (
        ("setrlimit", (ctypes.c_long(-1), ctypes.byref(invalid))),
        ("prlimit64", (ctypes.c_long(0), ctypes.c_long(-1), ctypes.byref(invalid), ctypes.c_void_p())),
    )
    for name, arguments in probes:
        number = lib.seccomp_syscall_resolve_name(name.encode("ascii"))
        if number == -1:
            raise ValueError("unknown resource syscall: " + name)
        ctypes.set_errno(0)
        if libc.syscall(ctypes.c_long(number), *arguments) != -1 or ctypes.get_errno() != errno.EPERM:
            raise RuntimeError("resource setter challenge failed: " + name)
    if (resource.getrlimit(resource.RLIMIT_NOFILE) != expected
            or libc.prlimit64(0, 7, None, ctypes.byref(observed)) != 0
            or (observed.current, observed.maximum) != expected):
        raise RuntimeError("descriptor resource budget changed during challenges")


BACKEND_USER = "azurelinux3s4-web-backend"
PROXY_USER = "azurelinux3s4-web-proxy"
SHARED_GROUP = "azurelinux3s4-web"
ROOT_UID = 0
ROOT_GID = 0
JOURNAL = "/run/systemd/journal/stdout"
BUFFER = 65536
IDLE_SECONDS = 30
TOTAL_SECONDS = 300
METADATA_DENIED = (
    # Landlock filesystem rights do not cover these metadata mutations.
    "chmod", "fchmod", "fchmodat", "fchmodat2",
    "chown", "fchown", "lchown", "fchownat",
    "utime", "utimes", "futimesat", "utimensat",
    "setxattr", "lsetxattr", "fsetxattr",
    "removexattr", "lremovexattr", "fremovexattr",
)
IPC_DENIED = (
    # No signal delivery, SysV/POSIX named IPC or kernel key operations are
    # needed for read/write forwarding. Incoming supervisor signals still work.
    "kill", "tkill", "tgkill", "rt_sigqueueinfo", "rt_tgsigqueueinfo", "pidfd_send_signal",
    "semget", "semop", "semtimedop", "semctl",
    "msgget", "msgsnd", "msgrcv", "msgctl",
    "shmget", "shmat", "shmdt", "shmctl",
    "mq_open", "mq_unlink", "mq_timedsend", "mq_timedreceive", "mq_notify", "mq_getsetattr",
    "add_key", "request_key", "keyctl",
)
DENIED = (
    "socket", "socketpair", "connect", "accept", "accept4",
    # Fast Open through sendto/sendmsg is also a connection initiation route.
    # Forward through read/write only; never permit caller-controlled flags.
    "sendto", "sendmsg", "sendmmsg", "recvmsg", "recvmmsg", "setsockopt", "ioctl",
    "pidfd_getfd", "io_uring_setup", "io_uring_enter", "io_uring_register", "bpf",
    "execve", "execveat", "clone", "clone3", "fork", "vfork", "unshare", "setns",
    "ptrace", "process_vm_readv", "process_vm_writev",
) + METADATA_DENIED + IPC_DENIED + DESCRIPTOR_DENIED + RESOURCE_DENIED


class Comparison(ctypes.Structure):
    _fields_ = [("arg", ctypes.c_uint), ("op", ctypes.c_int),
                ("a", ctypes.c_uint64), ("b", ctypes.c_uint64)]


def peer_credentials(stream):
    # SO_PEERCRED is a connect/listen-time observation, not executable identity
    # or evidence that the currently executing process still has these IDs.
    data = stream.getsockopt(socket.SOL_SOCKET, socket.SO_PEERCRED, 12)
    if len(data) != 12:
        raise ValueError("Unix peer credentials are incomplete")
    pid, uid, gid = struct.unpack("=iII", data)
    if pid <= 0 or uid == 0xffffffff or gid == 0xffffffff:
        raise ValueError("Unix peer credentials are unavailable")
    return pid, uid, gid


def process_identity():
    proxy = pwd.getpwnam(PROXY_USER)
    backend = pwd.getpwnam(BACKEND_USER)
    group = grp.getgrnam(SHARED_GROUP)
    if (proxy.pw_name != PROXY_USER or backend.pw_name != BACKEND_USER
            or group.gr_name != SHARED_GROUP
            or not 0 < proxy.pw_uid < 0xffffffff
            or not 0 < backend.pw_uid < 0xffffffff
            or proxy.pw_uid == backend.pw_uid
            or not 0 < group.gr_gid < 0xffffffff
            or pwd.getpwuid(proxy.pw_uid).pw_name != PROXY_USER
            or pwd.getpwuid(backend.pw_uid).pw_name != BACKEND_USER
            or grp.getgrgid(group.gr_gid).gr_name != SHARED_GROUP):
        raise ValueError("dedicated web account observations are inconsistent")
    if (os.getresuid() != (proxy.pw_uid,) * 3
            or os.getresgid() != (group.gr_gid,) * 3
            or not set(os.getgroups()) <= {group.gr_gid}):
        raise ValueError("web worker credentials differ from the dedicated identity")
    # Root, borrowed supplementary groups and retained capabilities are refused.
    # NSS/base/procfs are trusted inputs; this is not account creation/admission.
    with open("/proc/self/status", "rb") as stream:
        data = stream.read(16385)
    if len(data) > 16384:
        raise ValueError("process status exceeds the observation bound")
    records = {}
    for line in data.splitlines():
        key, separator, value = line.partition(b":")
        if separator and key in (b"Uid", b"Gid", b"CapInh", b"CapPrm", b"CapEff", b"CapBnd", b"CapAmb", b"NoNewPrivs"):
            if key in records:
                raise ValueError("duplicate process status observation")
            records[key] = value.split()
    if (records.get(b"Uid") != [str(proxy.pw_uid).encode()] * 4
            or records.get(b"Gid") != [str(group.gr_gid).encode()] * 4
            or records.get(b"NoNewPrivs") != [b"1"]):
        raise ValueError("process filesystem IDs or NNP observation refused")
    for key in (b"CapInh", b"CapPrm", b"CapEff", b"CapBnd", b"CapAmb"):
        values = records.get(key, [])
        if len(values) != 1 or len(values[0]) != 16 or values[0] != b"0" * 16:
            raise ValueError("process capability observation refused")
    return proxy.pw_uid, backend.pw_uid, group.gr_gid


def admit_logging():
    observations = []
    for descriptor in (1, 2):
        if not stat.S_ISSOCK(os.fstat(descriptor).st_mode):
            raise ValueError("only connected Unix journal logging descriptors are accepted")
        stream = socket.socket(fileno=descriptor)
        try:
            if (stream.family != socket.AF_UNIX or stream.type != socket.SOCK_STREAM
                    or stream.getsockopt(socket.SOL_SOCKET, socket.SO_ACCEPTCONN)
                    or stream.getpeername() != JOURNAL):
                raise ValueError("unexpected journal descriptor")
            peer = peer_credentials(stream)
            if peer[1:] != (ROOT_UID, ROOT_GID):
                raise ValueError("journal peer is not the expected root identity")
            observations.append(peer)
        finally:
            stream.detach()
    if observations[0] != observations[1]:
        raise ValueError("journal descriptors have different peers")


def inode_identity(value):
    return value.st_dev, value.st_ino, value.st_mode, value.st_uid, value.st_gid


def mount_identity(descriptor):
    with open(f"/proc/self/fdinfo/{descriptor}", "rb") as stream:
        data = stream.read(8193)
    if len(data) > 8192:
        raise ValueError("descriptor mount observation exceeds the bound")
    values = [line.split(b":", 1)[1].strip() for line in data.splitlines()
              if line.startswith(b"mnt_id:")]
    if len(values) != 1 or not values[0].isdigit():
        raise ValueError("descriptor mount identity is unavailable")
    return int(values[0])


def backend_root():
    return os.open("/", os.O_PATH | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC)


def backend_path(backend_uid, group_gid):
    # Fixed, alias-free path. O_PATH never opens a FIFO/device/socket for IO;
    # NOFOLLOW leaves symlinks as links so they cannot redirect this walk.
    descriptors = []
    try:
        root = backend_root()
        descriptors.append(root)
        trace = []
        for index, name in enumerate((None, "run", "azurelinux3s4-web", "http.sock")):
            if name is not None:
                descriptors.append(os.open(name, os.O_PATH | os.O_NOFOLLOW | os.O_CLOEXEC,
                                           dir_fd=descriptors[-1]))
            descriptor = descriptors[-1]
            value = os.fstat(descriptor)
            if index < 2:
                if not stat.S_ISDIR(value.st_mode) or value.st_uid != ROOT_UID or value.st_mode & 0o022:
                    raise ValueError("unprotected backend root or run ancestry")
            elif index == 2:
                if (not stat.S_ISDIR(value.st_mode) or value.st_uid != backend_uid
                        or value.st_gid != group_gid or stat.S_IMODE(value.st_mode) != 0o750):
                    raise ValueError("backend runtime directory identity or permissions refused")
            elif (not stat.S_ISSOCK(value.st_mode) or value.st_uid != backend_uid
                  or value.st_gid != group_gid or stat.S_IMODE(value.st_mode) != 0o666):
                raise ValueError("backend socket identity, kind or permissions refused")
            trace.append((inode_identity(value), mount_identity(descriptor)))
        # RuntimeDirectory may be a checked read-only bind in the worker. The
        # socket must be on that same mount; parent transitions are rechecked.
        if trace[-1][1] != trace[-2][1]:
            raise ValueError("backend socket has a separate mount")
        return descriptors, trace
    except BaseException:
        for descriptor in reversed(descriptors):
            os.close(descriptor)
        raise


def connect_backend(backend_uid, group_gid):
    descriptors, before = backend_path(backend_uid, group_gid)
    connection = None
    try:
        connection = socket.socket(socket.AF_UNIX)
        connection.settimeout(5)
        # Resolve the held socket inode through the trusted kernel fd link,
        # rather than reopening its original pathname for connection setup.
        connection.connect(f"/proc/self/fd/{descriptors[-1]}")
        peer = peer_credentials(connection)
        if peer[1:] != (backend_uid, group_gid):
            raise ValueError("backend listener credentials do not match the socket owner")
        after_descriptors, after = backend_path(backend_uid, group_gid)
        try:
            if before != after or any(inode_identity(os.fstat(fd)) != item[0]
                                      or mount_identity(fd) != item[1]
                                      for fd, item in zip(descriptors, before)):
                raise ValueError("backend ancestry/socket changed during admission")
        finally:
            for descriptor in reversed(after_descriptors):
                os.close(descriptor)
        if peer_credentials(connection) != peer:
            raise ValueError("backend peer credentials changed during admission")
        connection.setblocking(False)
        return connection
    except BaseException:
        if connection is not None:
            connection.close()
        raise
    finally:
        for descriptor in reversed(descriptors):
            os.close(descriptor)


def checked(result):
    if result < 0:
        raise OSError(-result, "relay seccomp operation refused")


def restrict(final):
    if platform.machine() not in ("x86_64", "aarch64"):
        raise ValueError("unsupported native architecture")
    libc = ctypes.CDLL(None, use_errno=True)
    libc.prctl.argtypes = [ctypes.c_int, ctypes.c_ulong, ctypes.c_ulong,
                          ctypes.c_ulong, ctypes.c_ulong]
    if libc.prctl(38, 1, 0, 0, 0):  # PR_SET_NO_NEW_PRIVS
        raise OSError(ctypes.get_errno(), "no-new-privileges refused")
    lib = ctypes.CDLL("libseccomp.so.2")
    lib.seccomp_init.argtypes = [ctypes.c_uint32]
    lib.seccomp_init.restype = ctypes.c_void_p
    lib.seccomp_syscall_resolve_name.argtypes = [ctypes.c_char_p]
    lib.seccomp_syscall_resolve_name.restype = ctypes.c_int
    lib.seccomp_rule_add_array.argtypes = [ctypes.c_void_p, ctypes.c_uint32, ctypes.c_int,
                                         ctypes.c_uint, ctypes.POINTER(Comparison)]
    lib.seccomp_attr_set.argtypes = [ctypes.c_void_p, ctypes.c_uint, ctypes.c_uint32]
    lib.seccomp_load.argtypes = [ctypes.c_void_p]
    lib.seccomp_release.argtypes = [ctypes.c_void_p]
    context = lib.seccomp_init(0x7fff0000)  # ALLOW; native ABI only, bad ABI kills.
    if not context:
        raise RuntimeError("seccomp_init failed")
    try:
        checked(lib.seccomp_attr_set(context, 4, 1))  # CTL_TSYNC, all current threads
        checked(lib.seccomp_attr_set(context, 2, 0x80000000))  # ACT_BADARCH: KILL_PROCESS
        if final:
            for name in DENIED:
                number = lib.seccomp_syscall_resolve_name(name.encode("ascii"))
                if number == -1:  # __NR_SCMP_ERROR; other negative values are pseudo IDs.
                    raise ValueError("unknown syscall: " + name)
                checked(lib.seccomp_rule_add_array(context, 0x50000 | errno.EPERM, number, 0, None))
            add_descriptor_rules(lib, context)
            add_resource_rules(lib, context)
        else:
            number = lib.seccomp_syscall_resolve_name(b"socket")
            if number == -1:
                raise ValueError("socket syscall unknown")
            for operation in (2, 6):  # SCMP_CMP_LT, GT: only AF_UNIX can be created.
                comparison = Comparison(0, operation, socket.AF_UNIX, 0)
                checked(lib.seccomp_rule_add_array(context, 0x50000 | errno.EAFNOSUPPORT,
                                                   number, 1, ctypes.byref(comparison)))
        checked(lib.seccomp_load(context))
        if libc.prctl(39, 0, 0, 0, 0) != 1 or libc.prctl(21, 0, 0, 0, 0) != 2:
            raise RuntimeError("kernel did not report NNP/filter mode")
    finally:
        lib.seccomp_release(context)


def verify_seal(connection):
    libc = ctypes.CDLL(None, use_errno=True)
    libc.connect.argtypes = [ctypes.c_int, ctypes.c_void_p, ctypes.c_uint]
    address = ctypes.create_string_buffer(16)  # Actual AF_UNSPEC disconnect challenge.
    if libc.connect(connection.fileno(), address, 16) != -1 or ctypes.get_errno() != errno.EPERM:
        raise RuntimeError("connect denial challenge failed")
    try:
        created = socket.socket(socket.AF_UNIX)
    except OSError as error:
        if error.errno != errno.EPERM:
            raise
    else:
        created.close()
        raise RuntimeError("socket denial challenge failed")
    connection.getpeername()  # The challenge must leave the accepted connection intact.


def verify_operations():
    # These calls cannot modify files, deliver a signal or create an IPC/key
    # object even if a rule is missing. Require the filter's EPERM rather than
    # the ordinary invalid-FD/argument error or successful signal-zero query.
    libc = ctypes.CDLL(None, use_errno=True)
    libc.syscall.argtypes = [ctypes.c_long]
    libc.syscall.restype = ctypes.c_long
    lib = ctypes.CDLL("libseccomp.so.2")
    lib.seccomp_syscall_resolve_name.argtypes = [ctypes.c_char_p]
    lib.seccomp_syscall_resolve_name.restype = ctypes.c_int
    challenges = (
        ("fchmod", (-1, 0)),
        ("kill", (os.getpid(), 0)),
        ("shmget", (0, 0, 0)),
        ("mq_getsetattr", (-1, 0, 0)),
        ("keyctl", (-1, 0, 0, 0, 0)),
    )
    for name, arguments in challenges:
        number = lib.seccomp_syscall_resolve_name(name.encode("ascii"))
        if number < 0:
            raise ValueError("operation challenge syscall unavailable: " + name)
        ctypes.set_errno(0)
        result = libc.syscall(ctypes.c_long(number), *(ctypes.c_long(value) for value in arguments))
        if result != -1 or ctypes.get_errno() != errno.EPERM:
            raise RuntimeError("operation denial challenge failed: " + name)


def confine_filesystem():
    # No allow rules: deny every known handled filesystem right. ABI3 adds
    # truncate, ABI5 device ioctl. Later network/scope fields stay zero. This
    # is a calling-thread layer; final TSYNC clone denial must precede the
    # single-task check. Metadata/O_PATH and already-open FDs remain separate.
    if (platform.machine() not in ("x86_64", "aarch64")
            or ctypes.sizeof(ctypes.c_void_p) != 8 or ctypes.sizeof(ctypes.c_long) != 8):
        raise ValueError("unsupported Landlock native architecture or ABI")
    libc = ctypes.CDLL(None, use_errno=True)
    libc.syscall.argtypes = [ctypes.c_long]
    libc.syscall.restype = ctypes.c_long
    libc.prctl.argtypes = [ctypes.c_int, ctypes.c_ulong, ctypes.c_ulong,
                          ctypes.c_ulong, ctypes.c_ulong]
    if libc.prctl(39, 0, 0, 0, 0) != 1 or libc.prctl(21, 0, 0, 0, 0) != 2:
        raise RuntimeError("filesystem confinement requires NNP and seccomp")
    # Linux x86_64 and asm-generic/aarch64 use these native syscall numbers.
    abi = libc.syscall(ctypes.c_long(444), ctypes.c_void_p(), ctypes.c_size_t(0), ctypes.c_uint(1))
    if abi < 0:
        raise OSError(ctypes.get_errno(), "Landlock ABI query refused")
    if abi < 3:
        raise ValueError("Landlock ABI3 or newer is required")
    with os.scandir("/proc/self/task") as tasks:
        observed = [entry.name for _, entry in zip(range(2), tasks)]
    if observed != [str(os.getpid())]:
        raise RuntimeError("filesystem confinement requires one live task")
    rights = (1 << 15) - 1
    if abi >= 5:
        rights |= 1 << 15
    attribute = ctypes.c_uint64(rights)  # Eight-byte handled_access_fs prefix.
    probe = os.open("/proc/self/status", os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC)
    try:
        if not stat.S_ISREG(os.fstat(probe).st_mode) or not os.read(probe, 1):
            raise ValueError("filesystem read challenge has no regular readable baseline")
        ruleset = libc.syscall(ctypes.c_long(444), ctypes.byref(attribute),
                               ctypes.c_size_t(ctypes.sizeof(attribute)), ctypes.c_uint(0))
        if ruleset < 0:
            raise OSError(ctypes.get_errno(), "Landlock ruleset creation refused")
        try:
            if libc.syscall(ctypes.c_long(446), ctypes.c_int(ruleset), ctypes.c_uint(0)) != 0:
                raise OSError(ctypes.get_errno(), "Landlock restriction refused")
        finally:
            os.close(ruleset)
        # Check both the namespace path and trusted kernel fd-link reopening.
        # Only EACCES after a successful baseline certifies this challenge.
        for path in ("/proc/self/status", f"/proc/self/fd/{probe}"):
            try:
                opened = os.open(path, os.O_RDONLY | os.O_CLOEXEC)
            except OSError as error:
                if error.errno != errno.EACCES:
                    raise
            else:
                os.close(opened)
                raise RuntimeError("filesystem read-denial challenge failed")
    finally:
        os.close(probe)
    return abi, rights


def forward(client, backend):
    # At most two BUFFER-sized queues; half-close each destination only after
    # its queued data drains. No connection setup, recvmsg or flagged send calls.
    streams = {client.fileno(): backend.fileno(), backend.fileno(): client.fileno()}
    objects = {stream.fileno(): stream for stream in (client, backend)}
    buffers = {descriptor: bytearray() for descriptor in streams}
    readable = set(streams)
    write_open = set(streams)
    started = last_progress = time.monotonic()
    with selectors.DefaultSelector() as selector:
        registered = set()
        while readable or any(buffers.values()):
            now = time.monotonic()
            remaining = min(started + TOTAL_SECONDS - now, last_progress + IDLE_SECONDS - now)
            if remaining <= 0:
                raise TimeoutError("relay connection deadline reached")
            for descriptor, destination in streams.items():
                events = 0
                if descriptor in readable and len(buffers[destination]) < BUFFER:
                    events |= selectors.EVENT_READ
                if buffers[descriptor]:
                    events |= selectors.EVENT_WRITE
                if events:
                    if descriptor in registered:
                        selector.modify(descriptor, events)
                    else:
                        selector.register(descriptor, events)
                        registered.add(descriptor)
                elif descriptor in registered:
                    selector.unregister(descriptor)
                    registered.remove(descriptor)
            for key, events in selector.select(remaining):
                descriptor = key.fd
                destination = streams[descriptor]
                if events & selectors.EVENT_READ:
                    try:
                        data = os.read(descriptor, BUFFER - len(buffers[destination]))
                    except BlockingIOError:
                        pass
                    else:
                        if data:
                            buffers[destination].extend(data)
                            last_progress = time.monotonic()
                        else:
                            readable.remove(descriptor)
                if events & selectors.EVENT_WRITE:
                    try:
                        count = os.write(descriptor, buffers[descriptor])
                    except BlockingIOError:
                        pass
                    else:
                        if count <= 0:
                            raise OSError("relay write made no progress")
                        del buffers[descriptor][:count]
                        last_progress = time.monotonic()
            for source, destination in streams.items():
                if source not in readable and not buffers[destination] and destination in write_open:
                    objects[destination].shutdown(socket.SHUT_WR)
                    write_open.remove(destination)


def prepare_client(descriptor):
    connection = socket.socket(fileno=descriptor)
    try:
        if (connection.family not in (socket.AF_INET, socket.AF_INET6)
                or connection.type != socket.SOCK_STREAM
                or connection.getsockopt(socket.SOL_SOCKET, socket.SO_ACCEPTCONN)):
            raise ValueError("an accepted IPv4/IPv6 stream is required")
        connection.getpeername()
        # Avoid implicit connection initiation from ordinary writes. Linux ABI:
        # TCP_FASTOPEN_CONNECT=30. An established socket cannot change this
        # option: observe zero, otherwise refuse. Sealing also denies setsockopt.
        if connection.getsockopt(socket.IPPROTO_TCP, 30) != 0:
            raise ValueError("Fast Open connect remains enabled")
        connection.setblocking(False)
        return connection
    except BaseException:
        connection.close()
        raise


def close_inherited():
    for descriptor in (1, 2):
        if stat.S_ISSOCK(os.fstat(descriptor).st_mode):
            stream = socket.socket(fileno=descriptor)
            try:
                if stream.family != socket.AF_UNIX:
                    raise ValueError("stdout/stderr cannot be inherited IP sockets")
            finally:
                stream.detach()
    libc = ctypes.CDLL(None, use_errno=True)
    libc.close_range.argtypes = [ctypes.c_uint, ctypes.c_uint, ctypes.c_uint]
    if libc.close_range(3, 0xffffffff, 0):
        raise OSError(ctypes.get_errno(), "cannot close extra inherited descriptors")


def close_runtime_extras(backend):
    # NSS/native libraries may retain descriptors during startup. Keep only
    # stdio and the checked backend, even after the final account lookup.
    descriptor = backend.fileno()
    if descriptor < 3:
        raise ValueError("backend descriptor overlaps standard IO")
    before = inode_identity(os.fstat(descriptor))
    libc = ctypes.CDLL(None, use_errno=True)
    libc.close_range.argtypes = [ctypes.c_uint, ctypes.c_uint, ctypes.c_uint]
    for first, last in ((3, descriptor - 1), (descriptor + 1, 0xffffffff)):
        if first <= last and libc.close_range(first, last, 0):
            raise OSError(ctypes.get_errno(), "cannot close startup lookup/extra descriptors")
    if inode_identity(os.fstat(descriptor)) != before:
        raise ValueError("backend descriptor changed during extra descriptor closure")


def main():
    try:
        if len(sys.argv) != 1:
            raise ValueError("no relay overrides are accepted")
        resource.setrlimit(resource.RLIMIT_CPU, (60, 70))
        resource.setrlimit(resource.RLIMIT_AS, (128 * 1024 * 1024,) * 2)
        resource.setrlimit(resource.RLIMIT_CORE, (0, 0))
        with RuntimeStartup() as startup:
            credentials = process_identity()
            admit_logging()
            close_inherited()
            bound_descriptors(FD_STARTUP_LIMIT)
            with prepare_client(0) as client:
                restrict(False)
                with connect_backend(credentials[1], credentials[2]) as backend:
                    if process_identity() != credentials:
                        raise ValueError("web account observations changed during startup")
                    observe_runtime()
                    protect_memory()
                    close_runtime_extras(backend)
                    descriptor_budget = bound_descriptors(FD_FORWARD_LIMIT, (0, 1, 2, backend.fileno()))
                    restrict(True)
                    verify_seal(client)
                    verify_operations()
                    verify_descriptors((client.fileno(), backend.fileno()))
                    verify_resource_limits(descriptor_budget)
                    confine_filesystem()
                    startup.disarm()
                    forward(client, backend)
    except (OSError, ValueError, RuntimeError, MemoryError, KeyError) as error:
        print("Web relay refused: " + str(error), file=sys.stderr)
        return 75
    return 0


if __name__ == "__main__":
    sys.exit(main())
